name: complement-mdlm
backbone: dit
parameterization: subs
time_conditioning: False
T: 0  # 0 (continuous time) / 1000 
subs_masking: False
causal_attention: False
ignore_bos: False
loss_type: elbo  # elbo, low_var

post_process_mode: orig  # orig / fp64 / efficient / efficient+fp64