name: partition-mdlm
backbone: encoder-decoder
parameterization: subs
time_conditioning: False
T: 0  # 0 (continuous time) / 1000 
subs_masking: False
causal_attention: False
ignore_bos: False
loss_type: elbo  # elbo, low_var
sampling_mode: efficient-uniform  # naive / efficient-uniform / efficient-non-uniform
post_process_mode: efficient  # efficient / efficient+fp64